services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - DATABASE_DSN=host=db port=5432 user=postgres password=justadummy dbname=testdb sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test-network

  db:
    image: my-postgres-image:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=justadummy
      - POSTGRES_DB=testdb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  integration-test:
    build:
      context: ./tests/integration
      dockerfile: Dockerfile
    depends_on:
      app:
        condition: service_started
    environment:
      - APP_HOST=app
      - APP_PORT=3000
    networks:
      - test-network

networks:
  test-network:
    driver: bridge